### ISSUE TITLE
Errors were encountered while processing:  linux-image-5.11.0-34-generic

### ISSUE THREAD

**Issue by aral** [elementary/appcenter#1660]
## What Happened

Update failed with error:

```
Errors were encountered while processing:
 linux-image-5.11.0-34-generic
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

(Full error log from manual `sudo apt upgrade` attempt on Terminal following failure in AppCenter is below.)

## Expected Behavior

Update should succeed.

## Steps to Reproduce

1. Hit update on Operating system updates

### Logs

```
Processing triggers for dbus (1.12.16-2ubuntu2.1) ...
Processing triggers for bamfdaemon (0.5.3+18.04.20180207.2-0ubuntu2) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for linux-image-5.11.0-34-generic (5.11.0-34.36~20.04.1) ...
/etc/kernel/postinst.d/initramfs-tools:
update-initramfs: Generating /boot/initrd.img-5.11.0-34-generic
W: Possible missing firmware /lib/firmware/i915/skl_guc_49.0.1.bin for module i915
W: Possible missing firmware /lib/firmware/i915/bxt_guc_49.0.1.bin for module i915
W: Possible missing firmware /lib/firmware/i915/kbl_guc_49.0.1.bin for module i915
W: Possible missing firmware /lib/firmware/i915/glk_guc_49.0.1.bin for module i915
W: Possible missing firmware /lib/firmware/i915/kbl_guc_49.0.1.bin for module i915
W: Possible missing firmware /lib/firmware/i915/kbl_guc_49.0.1.bin for module i915
W: Possible missing firmware /lib/firmware/i915/cml_guc_49.0.1.bin for module i915
W: Possible missing firmware /lib/firmware/i915/icl_guc_49.0.1.bin for module i915
W: Possible missing firmware /lib/firmware/i915/ehl_guc_49.0.1.bin for module i915
W: Possible missing firmware /lib/firmware/i915/ehl_guc_49.0.1.bin for module i915
W: Possible missing firmware /lib/firmware/i915/tgl_huc_7.5.0.bin for module i915
W: Possible missing firmware /lib/firmware/i915/tgl_guc_49.0.1.bin for module i915
W: Possible missing firmware /lib/firmware/i915/tgl_huc_7.5.0.bin for module i915
W: Possible missing firmware /lib/firmware/i915/tgl_guc_49.0.1.bin for module i915
W: Possible missing firmware /lib/firmware/i915/dg1_dmc_ver2_02.bin for module i915
I: The initramfs will attempt to resume from /dev/dm-2
I: (/dev/mapper/data-swap)
I: Set the RESUME variable to override this.
/etc/kernel/postinst.d/zz-update-grub:
Sourcing file `/etc/default/grub'
Sourcing file `/etc/default/grub.d/init-select.cfg'
Generating grub configuration file ...
Found linux image: /boot/vmlinuz-5.11.0-34-generic
Found initrd image: /boot/initrd.img-5.11.0-34-generic
Found linux image: /boot/vmlinuz-5.11.0-27-generic
Found initrd image: /boot/initrd.img-5.11.0-27-generic
Found linux image: /boot/vmlinuz-5.11.0-25-generic
Found initrd image: /boot/initrd.img-5.11.0-25-generic
Adding boot menu entry for UEFI Firmware Settings
/etc/grub.d/35_fwupd: line 5: /usr/share/grub: Is a directory
run-parts: /etc/kernel/postinst.d/zz-update-grub exited with return code 126
dpkg: error processing package linux-image-5.11.0-34-generic (--configure):
 installed linux-image-5.11.0-34-generic package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 linux-image-5.11.0-34-generic
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

## Platform Information

```
OS: elementary OS 6 Odin x86_64 
Host: LabTop Mk IV 
Kernel: 5.11.0-25-generic 
Uptime: 4 mins 
Packages: 2315 (dpkg), 48 (flatpak) 
Shell: fish 3.3.1 
Resolution: 1920x1080 
DE: Pantheon 
WM: Mutter(Gala) 
Terminal: io.elementary.t 
CPU: Intel i7-10710U (12) @ 4.700GHz 
GPU: Intel Device 9bca 
Memory: 1780MiB / 15875MiB
```

**Comment by aral** [comment]
PS. Tried `sudo apt --fix-broken install`, same result.

**Comment by aral** [comment]
I managed to fix this by removing `/etc/grub.d/35_fwupd`, which looks like firmware update script by StarLabs.

**Comment by Sean-StarLabs** [comment]
Fixed upstream - https://github.com/fwupd/fwupd/commit/92c8f0e727aafec6f2ba9df2f236ba6a19b66a30

We're building a new version :)

**Comment by aral** [comment]
@Sean-StarLabs Thanks :) Does this mean I should replace that script with your new version manually when it’s out? Is there an issue or forum post I can follow for updates? Thanks again.

**Comment by Sean-StarLabs** [comment]
fwupd issues are all here: https://github.com/fwupd/fwupd/issues. I'll log one on https://github.com/StarLabsLtd/firmware if it takes me longer than today to fix.

All that file does is create an entry in grub to start an update, which UEFI doesn't need unless you have a complex multi-boot setup with Windows.

**Comment by aral** [comment]
@Sean-StarLabs Thanks, Sean. Sounds like I can safely ignore it then :)

**Comment by 4jNsY6fCVqZv** [comment]
For me, this issue is still valid, but with 5.11.0-38-generic and no StarLabs device.
@davidmhewitt Any ideas how to solve this?

**Comment by Sean-StarLabs** [comment]
`sudo rm /etc/grub.d/35_fwupd` should do it :)

**Comment by 4jNsY6fCVqZv** [comment]
`rm: cannot remove '/etc/grub.d/35_fwupd': No such file or directory`

**Comment by 4jNsY6fCVqZv** [comment]
rm: cannot remove '/etc/grub.d/35_fwupd': No such file or directory
@Sean-StarLabs Thanks for getting back!

**Comment by Sean-StarLabs** [comment]
Must be a different issue then

**Comment by 4jNsY6fCVqZv** [comment]
```
update-initramfs: Generating /boot/initrd.img-5.11.0-38-generic
W: Possible missing firmware /lib/firmware/i915/skl_guc_49.0.1.bin for module i915
W: Possible missing firmware /lib/firmware/i915/bxt_guc_49.0.1.bin for module i915
W: Possible missing firmware /lib/firmware/i915/kbl_guc_49.0.1.bin for module i915
W: Possible missing firmware /lib/firmware/i915/glk_guc_49.0.1.bin for module i915
W: Possible missing firmware /lib/firmware/i915/kbl_guc_49.0.1.bin for module i915
W: Possible missing firmware /lib/firmware/i915/kbl_guc_49.0.1.bin for module i915
W: Possible missing firmware /lib/firmware/i915/cml_guc_49.0.1.bin for module i915
W: Possible missing firmware /lib/firmware/i915/icl_guc_49.0.1.bin for module i915
W: Possible missing firmware /lib/firmware/i915/ehl_guc_49.0.1.bin for module i915
W: Possible missing firmware /lib/firmware/i915/ehl_guc_49.0.1.bin for module i915
W: Possible missing firmware /lib/firmware/i915/tgl_huc_7.5.0.bin for module i915
W: Possible missing firmware /lib/firmware/i915/tgl_guc_49.0.1.bin for module i915
W: Possible missing firmware /lib/firmware/i915/tgl_huc_7.5.0.bin for module i915
W: Possible missing firmware /lib/firmware/i915/tgl_guc_49.0.1.bin for module i915
W: Possible missing firmware /lib/firmware/i915/dg1_dmc_ver2_02.bin for module i915
I: The initramfs will attempt to resume from /dev/dm-2
I: (/dev/mapper/data-swap)
I: Set the RESUME variable to override this.
Error 24 : Write error : cannot write compressed block 
E: mkinitramfs failure cpio 141 lz4 -9 -l 24
update-initramfs: failed for /boot/initrd.img-5.11.0-38-generic with 1.
dpkg: error processing package linux-firmware (--configure):
 installed linux-firmware package post-installation script subprocess returned error exit status 1
Setting up linux-image-5.11.0-40-generic (5.11.0-40.44~20.04.2) ...
dpkg: dependency problems prevent configuration of linux-image-generic-hwe-20.04:
 linux-image-generic-hwe-20.04 depends on linux-firmware; however:
  Package linux-firmware is not configured yet.

dpkg: error processing package linux-image-generic-hwe-20.04 (--configure):
 dependency problems - leaving unconfigured
Processing triggers for linux-image-5.11.0-40-generic (5.11.0-40.44~20.04.2) ...
/etc/kernel/postinst.d/initramfs-tools:
update-initramfs: Generating /boot/initrd.img-5.11.0-40-generic
W: Possible missing firmware /lib/firmware/i915/skl_guc_49.0.1.bin for module i915
W: Possible missing firmware /lib/firmware/i915/bxt_guc_49.0.1.bin for module i915
W: Possible missing firmware /lib/firmware/i915/kbl_guc_49.0.1.bin for module i915
W: Possible missing firmware /lib/firmware/i915/glk_guc_49.0.1.bin for module i915
W: Possible missing firmware /lib/firmware/i915/kbl_guc_49.0.1.bin for module i915
W: Possible missing firmware /lib/firmware/i915/kbl_guc_49.0.1.bin for module i915
W: Possible missing firmware /lib/firmware/i915/cml_guc_49.0.1.bin for module i915
W: Possible missing firmware /lib/firmware/i915/icl_guc_49.0.1.bin for module i915
W: Possible missing firmware /lib/firmware/i915/ehl_guc_49.0.1.bin for module i915
W: Possible missing firmware /lib/firmware/i915/ehl_guc_49.0.1.bin for module i915
W: Possible missing firmware /lib/firmware/i915/tgl_huc_7.5.0.bin for module i915
W: Possible missing firmware /lib/firmware/i915/tgl_guc_49.0.1.bin for module i915
W: Possible missing firmware /lib/firmware/i915/tgl_huc_7.5.0.bin for module i915
W: Possible missing firmware /lib/firmware/i915/tgl_guc_49.0.1.bin for module i915
W: Possible missing firmware /lib/firmware/i915/dg1_dmc_ver2_02.bin for module i915
I: The initramfs will attempt to resume from /dev/dm-2
I: (/dev/mapper/data-swap)
I: Set the RESUME variable to override this.
Error 24 : Write error : cannot write compressed block 
E: mkinitramfs failure cpio 141 lz4 -9 -l 24
update-initramfs: failed for /boot/initrd.img-5.11.0-40-generic with 1.
run-parts: /etc/kernel/postinst.d/initramfs-tools exited with return code 1
dpkg: error processing package linux-image-5.11.0-40-generic (--configure):
 installed linux-image-5.11.0-40-generic package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 linux-firmware
 linux-image-generic-hwe-20.04
 linux-image-5.11.0-40-generic
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by Sean-StarLabs** [comment]
Definitely different, you'll want to open a new issue :)

**Comment by 4jNsY6fCVqZv** [comment]
If you like, you are welcome to contribute to the new issue :)
